# Generated by Django 5.2 on 2025-04-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_aluno', models.CharField(max_length=50, verbose_name='Digite o nome do aluno')),
                ('last_name_aluno', models.CharField(max_length=50)),
                ('phone_number_aluno', models.CharField(max_length=15, verbose_name='Digite o N° do celular (xx) xxxxx-xxxx')),
                ('email_aluno', models.EmailField(max_length=100, verbose_name='E-mail do aluno')),
                ('cpf_aluno', models.CharField(max_length=11, unique=True, verbose_name='Informe o CPF do aluno')),
                ('birthday_aluno', models.DateField()),
                ('class_choices', models.CharField(blank=True, choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '1° Ano A'), ('2B', '1° Ano B'), ('2C', '1° Ano C'), ('3A', '1° Ano A'), ('3B', '1° Ano B'), ('3C', '1° Ano C')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo_professor', models.CharField(max_length=50, verbose_name='Digite o nome do professor')),
                ('phone_number_professor', models.CharField(max_length=15, verbose_name='Digite o N° do celular (xx) xxxxx-xxxx')),
                ('email_professor', models.EmailField(max_length=100, verbose_name='E-mail do professor')),
                ('cpf_professor', models.CharField(max_length=11, unique=True, verbose_name='Informe o CPF do professor')),
                ('birthday_professor', models.DateField()),
                ('padrinho_turma_professores', models.CharField(blank=True, choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '1° Ano A'), ('2B', '1° Ano B'), ('2C', '1° Ano C'), ('3A', '1° Ano A'), ('3B', '1° Ano B'), ('3C', '1° Ano C')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, verbose_name='Digite o N° do celular (xx) xxxxx-xxxx')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail do responsavel')),
                ('adress', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='Informe o CPF do Responsavel')),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma_name', models.CharField(max_length=50)),
                ('intinerario_name', models.CharField(max_length=50)),
                ('padrinho_name', models.CharField(max_length=50)),
                ('representante_name', models.CharField(max_length=50)),
                ('class_choice', models.CharField(blank=True, choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '1° Ano A'), ('2B', '1° Ano B'), ('2C', '1° Ano C'), ('3A', '1° Ano A'), ('3B', '1° Ano B'), ('3C', '1° Ano C')], max_length=2)),
                ('intinerario_choice', models.CharField(blank=True, choices=[('D.S.', 'Desenvolvimento de Sistemas'), ('C.N.', 'Ciencias da Natureza'), ('Jogos', 'Jogos Digitais')], max_length=8)),
            ],
        ),
    ]
