# Generated by Django 5.2 on 2025-04-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0002_rename_class_choice_turma_escolha_a_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_name_complete', models.CharField(max_length=100, null=True)),
                ('cpf_aluno', models.CharField(max_length=11, unique=True, verbose_name='Informe o CPF do Aluno')),
                ('birthday_aluno', models.DateField()),
                ('complete_name', models.CharField(max_length=100, null=True)),
                ('adress', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='Informe o CPF do Responsavel')),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='first_name_aluno',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='last_name_aluno',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='aluno',
            name='aluno_name_complete',
            field=models.CharField(max_length=100, null=True, verbose_name='Digite o nome completo do aluno'),
        ),
        migrations.AddField(
            model_name='responsavel',
            name='complete_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome_completo_professor',
            field=models.CharField(max_length=50, null=True, verbose_name='Digite o nome do professor'),
        ),
    ]
