# Generated by Django 5.2 on 2025-04-09 13:48

import secretaria.validador
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0003_contrato_remove_aluno_first_name_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf_aluno',
            field=models.CharField(max_length=11, unique=True, validators=[secretaria.validador.validar_cpf], verbose_name='Informe o CPF do aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='phone_number_aluno',
            field=models.CharField(max_length=15, validators=[secretaria.validador.telefone_validator], verbose_name='Digite o N° do celular (xx) xxxxx-xxxx'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[secretaria.validador.validar_cpf], verbose_name='Informe o CPF do Responsavel'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cpf_aluno',
            field=models.CharField(max_length=11, unique=True, validators=[secretaria.validador.validar_cpf], verbose_name='Informe o CPF do Aluno'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cpf_professor',
            field=models.CharField(max_length=11, unique=True, validators=[secretaria.validador.validar_cpf], verbose_name='Informe o CPF do professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone_number_professor',
            field=models.CharField(max_length=15, validators=[secretaria.validador.telefone_validator], verbose_name='Digite o N° do celular (xx) xxxxx-xxxx'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[secretaria.validador.validar_cpf], verbose_name='Informe o CPF do Responsavel'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[secretaria.validador.telefone_validator], verbose_name='Digite o N° do celular (xx) xxxxx-xxxx'),
        ),
    ]
