# Generated by Django 5.2 on 2025-04-09 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0004_alter_aluno_cpf_aluno_alter_aluno_phone_number_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='secretaria.responsavel'),
        ),
    ]
