# Generated by Django 5.2 on 2025-04-23 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0005_aluno_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='aluno_name_complete',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='birthday_aluno',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='complete_name',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cpf_aluno',
        ),
        migrations.AddField(
            model_name='contrato',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secretaria.aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_assinado',
            field=models.FileField(blank=True, null=True, upload_to='contratos_assinados/'),
        ),
    ]
