# Generated by Django 5.2 on 2025-05-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0006_remove_contrato_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='class_choices',
            field=models.CharField(blank=True, choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '2° Ano A'), ('2B', '2° Ano B'), ('2C', '2° Ano C'), ('3A', '3° Ano A'), ('3B', '3° Ano B'), ('3C', '3° Ano C')], max_length=2),
        ),
        migrations.AlterField(
            model_name='professor',
            name='padrinho_turma_professores',
            field=models.CharField(blank=True, choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '2° Ano A'), ('2B', '2° Ano B'), ('2C', '2° Ano C'), ('3A', '3° Ano A'), ('3B', '3° Ano B'), ('3C', '3° Ano C')], max_length=2),
        ),
        migrations.AlterField(
            model_name='turma',
            name='escolha_a_turma',
            field=models.CharField(blank=True, choices=[('1A', '1° Ano A'), ('1B', '1° Ano B'), ('1C', '1° Ano C'), ('2A', '2° Ano A'), ('2B', '2° Ano B'), ('2C', '2° Ano C'), ('3A', '3° Ano A'), ('3B', '3° Ano B'), ('3C', '3° Ano C')], max_length=2),
        ),
    ]
