# Generated by Django 5.1.7 on 2025-06-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0008_disciplina_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='turma_name',
        ),
    ]
