# Generated by Django 5.1.7 on 2025-06-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0009_remove_turma_turma_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='intinerario_name',
        ),
    ]
