# Generated by Django 5.1.7 on 2025-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0010_remove_turma_intinerario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='intinerario_name',
            field=models.CharField(default='Desenvolvimento de Sistemas', max_length=50),
        ),
        migrations.AddField(
            model_name='turma',
            name='turma_name',
            field=models.CharField(default='Turma Padrão', max_length=50),
        ),
    ]
