# Generated by Django 5.1.7 on 2025-06-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0011_turma_intinerario_name_turma_turma_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='intinerario_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma_name',
            field=models.CharField(max_length=50),
        ),
    ]
